# Generated by Django 6.0 on 2025-12-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_investimentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentos',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
