# Generated by Django 6.0 on 2025-12-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_investimentos_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='investimentos',
            name='img',
            field=models.CharField(default='', max_length=500),
        ),
    ]
